/* eslint-disable @typescript-eslint/no-explicit-any */
export type TourItem = {
  id: string;
  name: string;
  avatar: string;
  images: string[];
  priceNewAdult: number;
  priceNewChildren: number;
  priceNewBaby: number;
  stockAdult: number;
  stockChildren: number;
  stockBaby: number;
  position: number;
  status: string;
  createdAt: string;
  updatedAt: string;
  createdByFullName: string;
  updatedByFullName: string;
  category: string;
  priceAdult: number;
  priceChildren: number;
  priceBaby: number;
  information: string;
  locationsFrom: string[];
  locationsTo: string[];
  time: string;
  vehicle: string;
  departureDateFormat: string;
  schedules: any[];
};
